<?php include 'process.php' ?>
<html>
<head>
    <title>SEALIE | Your Build Guide</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <!-- Navigation Header -->
    <header class="header" id="header">
        <nav class="nav-container">
            <a href="#home" class="logo">
                <div class="logo-icon">
                    <div class="logo-prism">
                        <div class="prism-shape"></div>
                    </div>
                </div>
                <span class="logo-text">
                    <span class="prism">SEA</span>
                    <span class="flux">LIE</span>
                </span>
            </a>
            
            <ul class="nav-menu" id="navMenu">
                <li><a href="#home" class="nav-link active">Home</a></li>
                <li><a href="#about" class="nav-link">About</a></li>
                <li><a href="#contact" class="nav-link">Contact</a></li>
                <li><a href="Login.php">Login</a></li>
            </ul>
            
            <div class="menu-toggle" id="menuToggle">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </nav>
    </header>

    <!-- Hero Section with 3D Carousel -->
    <section class="hero" id="home">
        <?php include 'carousel.php' ?>
            <div class="carousel-controls">
                <button class="carousel-btn" id="prevBtn">‹</button>
                <button class="carousel-btn" id="nextBtn">›</button>
            </div>
    </section>

    <!-- NEW: Prism Philosophy Section (About) -->
    <section class="philosophy-section" id="about">
        <div class="philosophy-container">
            <div class="prism-line"></div>
            
            <h2 class="philosophy-headline">
                Welcome home,<br>Traveler!
            </h2>
            
            <p class="philosophy-subheading">
                Struggling with building your characters and team comps? Rest assured!<br>
                At Sealie, we'll be guiding you through complex build problems and simplify it for you!
            </p>
            
            <div class="philosophy-pillars">
                <div class="pillar">
                    <div class="pillar-icon">⚔️</div>
                    <h3 class="pillar-title">SYNERGY</h3>
                    <p class="pillar-description">
                        Evaluate real-time reaction compatibility, elemental resonances, and advanced buffs like Nightsoul and Hexerei to unlock maximum team potential.
                    </p>
                </div>
                
                <div class="pillar">
                    <div class="pillar-icon">🔬</div>
                    <h3 class="pillar-title">PRECISION</h3>
                    <p class="pillar-description">
                        Stop guessing substats. Get exact artifact stat benchmarks, main-stat priorities, and ER thresholds tailored to your specific character builds.
                    </p>
                </div>
                
                <div class="pillar">
                    <div class="pillar-icon">✨</div>
                    <h3 class="pillar-title">ADAPTABILITY</h3>
                    <p class="pillar-description">
                        Smart recommendations built around your actual roster and inventory. Optimize team setups using the characters and gear you already own.
                    </p>
                </div>
            </div>
            
            <div class="philosophy-particles" id="particles">
                <!-- Particles will be generated by JavaScript -->
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section class="contact-section" id="contact">
        <div class="section-header">
            <h2 class="section-title">Initialize Connection</h2>
            <p class="section-subtitle">Got any feedback or report? Write your thoughts below!</p>
        </div>
        
        <div class="contact-container">
            <div class="contact-info">
                <a href="link" class="info-item">
                    <div class="info-icon">
  <img src="storage/icons/discord-svgrepo-com.svg" class="svg-putih" width="24" height="24">
</div>
                    <div class="info-text">
                        <h4>Discord</h4>
                        <p>shaasluv</p>
                    </div>
                </a>
                
                <a href="link" class="info-item">
                    <div class="info-icon">💌</div>
                    <div class="info-text">
                        <h4>Email</h4>
                        <p>sealie.co@gmail.com</p>
                    </div>
                </a>
                
                <a href="link" target="_blank" class="info-item">
                    <div class="info-icon"></div>
                    <div class="info-text">
                        <h4>Threads</h4>
                        <p>sealie.co</p>
                    </div>
                </a>
            </div>
            
            <form class="contact-form" id="contactForm">
                <div class="form-group">
                    <label for="name">Username</label>
                    <input type="text" id="name" name="name" required>
                </div>
                
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" id="email" name="email" required>
                </div>
                
                <div class="form-group">
                    <label for="subject">Subject</label>
                    <input type="text" id="subject" name="subject" required>
                </div>
                
                <div class="form-group">
                    <label for="message">Message</label>
                    <textarea id="message" name="message" required></textarea>
                </div>
                
                <button type="submit" class="submit-btn">Send Message</button>
            </form>
        </div>
    </section>

    <!-- Footer -->
    <footer class="footer">
        <div class="footer-content">
            <div class="footer-brand">
                <div class="footer-logo">
                    <div class="logo-icon">
                        <div class="logo-prism">
                            <div class="prism-shape"></div>
                        </div>
                    </div>
                    <span class="logo-text">
                        <span class="prism">SEA</span>
                        <span class="flux">LIE</span>
                    </span>
                </div>
                <p class="footer-description">
                    Refracting complex challenges into brilliant solutions through the convergence of art, science, and technology.
                </p>
                <div class="footer-social">
                    <a href="#" class="social-icon">DC</a>
                    <a href="#" class="social-icon">X</a>
                    <a href="#" class="social-icon">T</a>
                </div>
            </div>
            
            <div class="footer-section">
                <h4>Features</h4>
                <div class="footer-links">
                    <a href="#">Artifact & Stat Guide</a>
                    <a href="#">Team Synergy Meter</a>
                    <a href="#">Buff & Talent Tracker</a>
                    <a href="#">Smart Roster Builder</a>
                </div>
            </div>
            
            <div class="footer-section">
                <h4>Community</h4>
                <div class="footer-links">
                    <a href="#">Join Discord</a>
                    <a href="#">Report a Bug / Feedback</a>
                    <a href="#">Feature Request</a>
                    <a href="#">Contact Us</a>
                </div>
            </div>
            
            <div class="footer-section">
                <h4>Resources</h4>
                <div class="footer-links">
                    <a href="#">Game Version Patch Notes</a>
                    <a href="#">FAQ</a>
                    <a href="#">Privacy Policy</a>
                    <a href="#">Disclaimer</a>
                </div>
            </div>
        </div>
        
        <div class="footer-bottom">
            <div class="copyright">
                © 2026 SEALIE. All rights reserved.
            </div>
            <div class="footer-credits">
                SEALIE is not affiliated with or endorsed by Hoyoverse.<br>
                Genshin Impact and all related assets are trademarks of Hoyoverse.
            </div>
        </div>
    </footer>
<script src="templatemo-prism-scripts.js"></script>
</body>
</html>